# Laboratorium 11.
## Faktoryzacja QR

### 1. Implementacja


In [8]:
import numpy as np

def qr_factorisation(A):
    n = A.shape[0]
    Q = np.zeros((n,n))
    R = np.zeros((n,n))

    for k in range(n):
        uk = A[:, k]
        for i in range(k):
            R[i,k] =np.dot(Q[:,i], A[:, k]) 
            uk = uk - R[i,k] * Q[:,i]

        R[k, k] = np.linalg.norm(uk)
        Q[:, k] = uk / R[k, k]
    
    return Q, R

A = np.array([[4.0, 2.0], [5.0, 8.0]])
Q, R = qr_factorisation(A)

print("My Q:")
print(Q)
print("My R:")
print(R)

Q,R = np.linalg.qr(A)
print("Lib Q:")
print(Q)
print("Lib R:")
print(R)

My Q:
[[ 0.62469505 -0.78086881]
 [ 0.78086881  0.62469505]]
My R:
[[6.40312424 7.49634057]
 [0.         3.43582276]]
Lib Q:
[[-0.62469505 -0.78086881]
 [-0.78086881  0.62469505]]
Lib R:
[[-6.40312424 -7.49634057]
 [ 0.          3.43582276]]


Jedyna różnica jest względem modułu, co wydaje mi się że nie stanowi problemu

### 2. Testy



In [14]:
def compare_results(M):
    n = M.shape[0]
    lib_Q, lib_R = np.linalg.qr(M)
    my_Q, my_R = qr_factorisation(M)

    highest_diff_Q = 0
    highest_diff_R = 0

    for i in range(n):
        for j in range(n):
            highest_diff_Q = max(highest_diff_Q, abs(abs(lib_Q[i,j]) - abs(my_Q[i,j])))
            highest_diff_R = max(highest_diff_R, abs(abs(lib_R[i,j]) - abs(my_R[i,j])))
    
    print(f"Matrix size: {n}\n highest diff for Q: {highest_diff_Q}\n highest diff for R: {highest_diff_R}")

for n in range(10,101,10):
    compare_results(np.random.randint(1,100,(n,n)))

Matrix size: 10
 highest diff for Q: 4.107825191113079e-15
 highest diff for R: 9.947598300641403e-14
Matrix size: 20
 highest diff for Q: 5.806466418789569e-14
 highest diff for R: 1.1368683772161603e-12
Matrix size: 30
 highest diff for Q: 3.542999227335031e-14
 highest diff for R: 1.4122036873231991e-12
Matrix size: 40
 highest diff for Q: 4.315992008230296e-14
 highest diff for R: 1.4779288903810084e-12
Matrix size: 50
 highest diff for Q: 1.6311951789305112e-12
 highest diff for R: 4.163780431554187e-12
Matrix size: 60
 highest diff for Q: 5.450084827884893e-13
 highest diff for R: 4.0181191707233666e-12
Matrix size: 70
 highest diff for Q: 7.786826738964692e-14
 highest diff for R: 6.0964566728216596e-12
Matrix size: 80
 highest diff for Q: 5.848654893725325e-13
 highest diff for R: 1.552891149003699e-11
Matrix size: 90
 highest diff for Q: 1.4881151866319442e-13
 highest diff for R: 2.0602186623364105e-11
Matrix size: 100
 highest diff for Q: 1.1052964099533824e-13
 highest diff

Wyniki (względem modułu), są te same względem arytmetyki zmiennoprzecinkowej

(DALEJ NIE ROBIE :))

### 2. Rozwiązywanie układów równań metodą QR

In [16]:
def solve_overdetermined_qr(A, b):
    Q, R = np.linalg.qr(A)
    
    Qt_b = np.dot(Q.T, b)
    
    x = np.linalg.solve(R[:A.shape[1], :], Qt_b[:A.shape[1]])
    
    return x

x = np.array([i for i in range(-5,6)])

y = np.array([2,7,9,12,13,14,14,13,10,8,4]).T

A = np.vstack([np.ones_like(x), x, x**2]).T
    
alpha = solve_overdetermined_qr(A, y)
print("Współczynniki α:", alpha)

Współczynniki α: [13.97202797  0.18181818 -0.43356643]
